# coding=utf-8
"""
Created on 2022, Jan 1st
@author: patrice journoud
"""
import os.path
import datetime
import bokeh
import tornado
from bokeh.application.handlers import FunctionHandler
from bokeh.server.server import Server
from bokeh.util.browser import view

from tornado.options import options
from bokeh.embed import server_document
from bokeh.layouts import layout
from qt3.handlers import StartHandler
from qt3.constants import APP_ROOT

from qt3.source.view.game import UiCells

APP_PORT = options.as_dict()['port']
SERVER_PORT = options.as_dict()['server_port']
APP_URL_BASENAME = options.as_dict()['app url basename']
SERVER_URL = options.as_dict()['server url']
AUTOLOAD_SERVER_URL = options.as_dict()['autoload_server_url']


class PlayHandler(tornado.web.RequestHandler):

    @staticmethod
    def modify_doc(doc):
        board = UiCells()
        board_layout = board.get_layout()
        my_layout = layout(board_layout)
        doc.add_root(my_layout)

    _bokeh_app = None

    def get(self):

        script = \
            server_document(
                url=AUTOLOAD_SERVER_URL,
            )

        self.render(
            'start.html',
            active_page='inks_upload',
            script=script,
        )

    def post(self):
        script = \
            server_document(
                url=AUTOLOAD_SERVER_URL,
            )

        self.render(
            'play.html',
            script=script,
        )


class Application(tornado.web.Application):
    def __init__(self):

        handlers = [
            (r"/{}".format(APP_URL_BASENAME), StartHandler),
            (r"/{}/play".format(APP_URL_BASENAME), PlayHandler),
        ]

        settings = dict(
                template_path=os.path.join(APP_ROOT, "web"),
                static_path=os.path.join(APP_ROOT, "static"),
                xsrf_cookies=True,
                # NOTE: some random value as secret (i.e. generated by uuid4())
                cookie_secret="32oETzKXQAGaYdkL5gEmGeJJFuYh7EQnp2XdTP1o/Vo=",
        )
        super(Application, self).__init__(handlers, **settings)


http_server = \
    tornado.httpserver.HTTPServer(
        Application(),
        max_header_size=100000000,
        max_body_size=1000000000,
    )
http_server.listen(options.port)
io_loop = tornado.ioloop.IOLoop.current()

bokeh_app = \
    bokeh.application.Application(
        FunctionHandler(
            PlayHandler.modify_doc
        )
    )
bokeh_server = \
    Server(
        {'/{}'.format(SERVER_URL): bokeh_app},
        port=SERVER_PORT,
        io_loop=io_loop,
        allow_websocket_origin=[
            'localhost:{}'.format(APP_PORT),
        ],
        secret_key=str(datetime.datetime.now()),
        generate_session_ids=True,
    )
bokeh_server.start()

io_loop.add_callback(
    view,
    "http://localhost:{}/{}".format(
        APP_PORT,
        APP_URL_BASENAME
    )
)
